### ISSUE TITLE
KeyError in pull-request-responsibility

### ISSUE THREAD

**Issue by connorkuehl** [enarx/bot#110]
Failure seen on a [recent PR to koine](https://github.com/enarx/koine/pull/15/checks?check_run_id=1539356106). I've attached the log to this issue since I don't know how long GitHub Actions retains them otherwise. [PR](https://github.com/enarx/koine/pull/15)

<details>
<summary>
Log
</summary>
<pre>
2020-12-11T19:33:25.1967487Z ##[section]Starting: Request a runner to run this job
2020-12-11T19:33:25.5600076Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'ubuntu-latest'
2020-12-11T19:33:25.5600204Z Can't find any online and idle self-hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2020-12-11T19:33:25.5600395Z Found online and idle hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2020-12-11T19:33:25.6762487Z ##[section]Finishing: Request a runner to run this job
2020-12-11T19:33:32.9545410Z Current runner version: '2.274.2'
2020-12-11T19:33:32.9573903Z ##[group]Operating System
2020-12-11T19:33:32.9574643Z Ubuntu
2020-12-11T19:33:32.9575029Z 18.04.5
2020-12-11T19:33:32.9575362Z LTS
2020-12-11T19:33:32.9575783Z ##[endgroup]
2020-12-11T19:33:32.9576208Z ##[group]Virtual Environment
2020-12-11T19:33:32.9576745Z Environment: ubuntu-18.04
2020-12-11T19:33:32.9577168Z Version: 20201129.1
2020-12-11T19:33:32.9577978Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20201129.1/images/linux/Ubuntu1804-README.md
2020-12-11T19:33:32.9578754Z ##[endgroup]
2020-12-11T19:33:32.9581208Z Prepare workflow directory
2020-12-11T19:33:33.0736041Z Prepare all required actions
2020-12-11T19:33:33.0747054Z Getting action download info
2020-12-11T19:33:33.3184627Z Download action repository 'actions-automation/pull-request-responsibility@main'
2020-12-11T19:33:35.2113552Z ##[group]Run actions-automation/pull-request-responsibility@main
2020-12-11T19:33:35.2114547Z with:
2020-12-11T19:33:35.2115449Z   actions: request,assign,copy-labels-linked,merge
2020-12-11T19:33:35.2116378Z   reviewers: reviews
2020-12-11T19:33:35.2116915Z   num_to_request: 3
2020-12-11T19:33:35.2117403Z env:
2020-12-11T19:33:35.2118216Z   BOT_TOKEN: ***
2020-12-11T19:33:35.2118731Z ##[endgroup]
2020-12-11T19:33:35.4340112Z  --- MERGE --- 
2020-12-11T19:33:35.9371880Z  --- COPY-LABELS-LINKED --- 
2020-12-11T19:33:35.9377877Z enarx/koine#15:
2020-12-11T19:33:36.5908099Z  --- REQUEST --- 
2020-12-11T19:33:37.0809557Z Traceback (most recent call last):
2020-12-11T19:33:37.0811818Z   File "/home/runner/work/_actions/actions-automation/pull-request-responsibility/main/src/request", line 166, in <module>
2020-12-11T19:33:37.0813295Z     migrate(requesting, suggested, len(requesting) + 1) # Get one suggested.
2020-12-11T19:33:37.0815169Z   File "/home/runner/work/_actions/actions-automation/pull-request-responsibility/main/src/request", line 87, in migrate
2020-12-11T19:33:37.0816433Z     status = availability[one]
2020-12-11T19:33:37.0817318Z KeyError: 'MikeCamel'
2020-12-11T19:33:37.1168576Z ##[error]Process completed with exit code 1.
2020-12-11T19:33:37.1211795Z Cleaning up orphan processes
</pre>
</details>

**Comment by mbestavros** [comment]
@connorkuehl This should be fixed in https://github.com/actions-automation/pull-request-responsibility/commit/a0a47d89fc0d7cf581c930ea9179dc8ca5f89ba1. Thanks for the report!
